services:
  primary:
    build: ./primary
    image: aps08-replication-primary
    container_name: aps08-primary
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  replica:
    build: ./replica
    image: aps08-replication-replica
    container_name: aps08-replica
    depends_on:
      primary:
        condition: service_healthy
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
